name: 'Test Suite'

on:
  workflow_dispatch:
    inputs:
      atlas_cloud_env:
        description: 'Atlas cloud environment used, can be either `dev` or `qa`, empty for `dev`'     
        type: string
        required: false
  workflow_call:
    inputs:
      atlas_cloud_env:
        description: 'Atlas cloud environment used, can be either `dev` or `qa`, empty for `dev`'     
        type: string
        required: false
  schedule:
    # https://crontab.guru/#0_0_2-31_*_0
    - cron: "9,14,19,24,29 1 * 1 *" # expecting qa
    - cron: "5,10,15,20,25 1 2-31 1 1-6" # expecting dev
   

jobs:
  day_of_week:
    runs-on: ubuntu-latest
    outputs:
      day: ${{ steps.set_day.outputs.day }}
    steps:
      - name: set day
        id: set_day
        run: |
          echo "day=$(date +'%a')"
          echo "workflow=${{ github.workflow}}"
          echo "day=$(date +'%a')" >> $GITHUB_OUTPUT
  before_tests:
    runs-on: ubuntu-latest
    needs: day_of_week
    if : ${{ needs.day_of_week.outputs.day != 'Fri' }}
    name: Before Tests
    env:
      atlas_cloud_env: ${{ inputs.atlas_cloud_env || github.event.schedule == '9,14,19,24,29 * * * *' && 'qa' || 'dev' }}
    steps:
      - run: |
          echo "cleaning up tests"

  tests:
    needs: before_tests
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "running tests"