name: 'Test Suite'

on:
  workflow_dispatch:
    inputs:
      atlas_cloud_env:
        description: 'Atlas cloud environment used, can be either `dev` or `qa`, empty for `dev`'     
        type: string
        required: false
  workflow_call:
    inputs:
      atlas_cloud_env:
        description: 'Atlas cloud environment used, can be either `dev` or `qa`, empty for `dev`'     
        type: string
        required: false
  schedule:
    # https://crontab.guru/#0_0_2-31_*_0
    - cron: "9,14,19,24,29 1 * 1 *" # expecting qa
    - cron: "5,10,15,20,25 1 2-31 1 1-6" # expecting dev
   

jobs:
  day_of_month:
    runs-on: ubuntu-latest
    outputs:
      first_day_of_month: ${{ steps.set_day.outputs.day }}
    steps:
      - name: set day
        id: set_day
        run: |
          echo "day=$(date +'%d')"
          echo "day=$(date +'%d')" >> $GITHUB_OUTPUT


  tests:
    runs-on: ubuntu-latest
    needs: day_of_month
    if : ${{ needs.day_of_month.outputs.first_day_of_month == '18' }}
    name: tests-output-of-atlas-cloud-env
    env:
      atlas_cloud_env: ${{ inputs.atlas_cloud_env || github.event.schedule == '9,14,19,24,29 * * * *' && 'qa' || 'dev' }}
    steps:
      - run: |
          echo $atlas_cloud_env
          echo ${{ github.event.schedule }}
