name: 'Test Suite'

# Runs acceptance and migrations tests with a set of terraform versions and provider versions (used for migration tests). This worflow is scheduled daily except Saturdays, but can also be run manually.
on:
  workflow_dispatch:
    inputs:
      atlas_cloud_env:
        description: 'Atlas cloud environment used, can be either `dev` or `qa`, empty for `dev`'     
        type: string
        required: false

  schedule:
    # https://crontab.guru/#0_0_2-31_*_0
    - cron: "53 10 2-31 * 1-6" # expecting qa
    - cron: "54 10 2-31 * 1-6" # expecting dev
   

jobs:
  tests:
    runs-on: ubuntu-latest
    name: tests-output-of-atlas-cloud-env
    env:
      atlas_cloud_env: ${{ inputs.atlas_cloud_env || github.event.schedule == '53 10 2-31 * 1-6' && 'qa' || 'dev' }}
    steps:
      - run: echo $atlas_cloud_env
